const mockDevices = [
  {
    id: 'nanopet',
    name: 'NanoPet',
    emoji: '🐾',
    type: 'AI Pet',
    status: 'Online',
    battery: 82,
    energy: 85,
    mode: 'Care & Chat',
    description: 'Your pocket buddy who learns and loves to play.',
    personality: 'Friendly',
    mood: 'Happy',
    playMode: 'Care & Chat',
    xp: 320,
    stars: 4,
    lastActivity: '2 min ago',
    accentLabel: 'Companion',
    accentColor: '#FF6B9D',
    kidActions: ['Feed', 'Talk', 'Glow'],
    safetyNote: 'Use gentle play mode indoors.',
    favoriteMission: 'Teach NanoPet a glow trick',
    actions: ['Voice', 'Lights']
  },
  {
    id: 'skyhawk',
    name: 'SkyHawk',
    emoji: '🛸',
    type: 'Drone',
    status: 'Online',
    battery: 64,
    energy: 72,
    mode: 'Explore & Fly',
    description: 'Quick scout ready to explore the skies safely.',
    personality: 'Brave',
    mood: 'Ready',
    playMode: 'Explore & Fly',
    xp: 470,
    stars: 5,
    lastActivity: '8 min ago',
    accentLabel: 'Patrol',
    accentColor: '#4ECDC4',
    kidActions: ['Fly', 'Scout', 'Return'],
    safetyNote: 'Fly only in safe open spaces.',
    favoriteMission: 'Guide SkyHawk back home',
    actions: ['Auto', 'Lights']
  },
  {
    id: 'cyberdog',
    name: 'CyberDog',
    emoji: '🐶',
    type: 'Robot Dog',
    status: 'Standby',
    battery: 41,
    energy: 55,
    mode: 'Tricks & Patrol',
    description: 'Loyal four-legged friend built for fun and safety.',
    personality: 'Loyal',
    mood: 'Excited',
    playMode: 'Tricks & Patrol',
    xp: 610,
    stars: 5,
    lastActivity: '14 min ago',
    accentLabel: 'Guard',
    accentColor: '#FFE66D',
    kidActions: ['Walk', 'Follow', 'Guard'],
    safetyNote: 'Keep clear space around moving toys.',
    favoriteMission: 'Walk CyberDog safely',
    actions: ['Voice', 'Return']
  }
];

module.exports = mockDevices;
